### ISSUE TITLE
As queries devem estar na classe repository

### ISSUE THREAD

**Issue by manoelcampos** [trasherdave/busca_voos#8]
Se você tem uma classe VooRepository, consultas como esta abaixo devem estar em métodos desta classe.
Isto tem a ver com o princípio [Separation of Concerns (SoC)](https://www.devmedia.com.br/amadurecendo-com-separation-of-concerns/18699), ou separação de preocupações, onde 
coisas distintas devem estar em locais distintos.
Acesso ao BD deve estar em classes DAO/Repository. 
O controller não deve ter código pra isso, a não ser que queira fazer algo realmente simples
e não queira se preocupar com isso.

https://github.com/trasherdave/busca_voos/blob/7f5e1436953c5369added7aee05e16f8163c2265/src/main/java/com/example/david/controller/VooResource.java#L83

**Comment by trasherdave** [comment]
Corrigido, excelente sugestão!
